### ISSUE TITLE
SyntaxError thrown while displaying exception in first example

### ISSUE THREAD

**Issue by joshbode** [CircleUp/exception-reports#7]
I'm getting a `SyntaxError` generated while displaying the exception from the first example.

I placed this in `testing.py`:
```python
import logging
import sys
from logging.config import dictConfig

from exception_reports.logs import uncaught_exception_handler, DEFAULT_LOGGING_CONFIG

# configure logging to use our filter and formatter
dictConfig(DEFAULT_LOGGING_CONFIG)

logger = logging.getLogger(__name__)

# configure uncaught exceptions to be logged
sys.excepthook = uncaught_exception_handler

raise Exception("YOLO!!!!")
```

Then ran it:
```bash
$ python3 --version
Python 3.6.4

$ python3 testing.py
Error in sys.excepthook:
Traceback (most recent call last):
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.6/site-packages/jinja2/filters.py", line 495, in do_pprint
    return pformat(value, verbose=verbose)
  File "/usr/local/lib/python3.6/site-packages/jinja2/utils.py", line 182, in pformat
    from pretty import pretty
  File "/usr/local/lib/python3.6/site-packages/pretty.py", line 165
    '''
      ^
SyntaxError: invalid syntax

Original exception was:
Traceback (most recent call last):
  File "/tmp/foo.py", line 16, in <module>
    raise Exception("YOYO!!!")
Exception: YOYO!!!
```

**Comment by brycedrennan** [comment]
Happy to see someone using the library! what was the issue?

**Comment by joshbode** [comment]
Sorry, should have checked - the exception is in `pretty`:
```
$ ipython3
In [1]: import pretty
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-02c420060202>", line 1, in <module>
    import pretty

  File "/usr/local/lib/python3.6/site-packages/pretty.py", line 165
    '''

^
SyntaxError: invalid syntax
```

**Comment by joshbode** [comment]
Success?
```bash
$ pip3 install pretty-py3
$ python3 testing.py
2018-03-28 15:28:20,843 13685 [ERROR] exception_reports.logs.uncaught_exception_handler: Uncaught Exception; error_report="/tmp/python-error-reports/2018-03-28_04:28:20.872809+00:00_0bff211295344a9b9992d10a161e6d22.html"
Traceback (most recent call last):
  File "/tmp/foo.py", line 16, in <module>
    raise Exception("YOYO!!!")
Exception: YOYO!!!
```

**Comment by brycedrennan** [comment]
yep - note the filepath at the far right of the error message

**Comment by joshbode** [comment]
Indeed!

**Comment by joshbode** [comment]
so, `jinja2` uses `pretty` (if available) but something else on my machine (not sure what) had installed a version of `pretty` that is incompatible with Python 3.
Solution is:
```
$ pip3 install pretty-py3
```

**Comment by joshbode** [comment]
Also, really like what you've built - I'm going to try it out on a project where tracking exceptions in logs is generally a drag (when is it not!) and let you know if I have any issues.

**Comment by brycedrennan** [comment]
That would be great. Thanks!
